name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  show-caller:
    if: ${{ startsWith(github.ref, 'refs/heads/feature/') }}
    uses: './.github/workflows/reusable.yaml'
    with:
      who-call: 'CI'

  show-files:
    name: Show files
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository 
        uses: actions/checkout@v4 

      - name: show files
        run: |
          echo "Files in the repository:"
          ls ${{ github.workspace }}

  show-actor:
    name: Show actor
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    steps:
      - name: Show actor
        run: echo "The actor is ${{ github.actor }}"
