name: Reusable
on:
  workflow_call:
    inputs:
      who-call:
        description: 'Who call this workflow'
        required: true
        type: string
jobs:
  show-caller:
    name: Show caller
    runs-on: ubuntu-latest
    steps:
      - name: Show caller
        run: echo "The caller is ${{ inputs.who-call }}"
